const Menu = [{
        image: "./img/i2.jpg",
        name: "Made By Johnny Women's Solid Short Sleeve Boat Neck V Neck Dolman Top..",
        number: "3,381",
        disc: "-18%",
        category: "women",
        price: "599",
        place: "Ships to India ",
    },

    {
        image: "./img/h1.webp",
        name: "Goodthreads Men's Slim-Fit Short-Sleeve Printed Poplin Shirt",
        number: "5,781",
        disc: "-30%",
        category: "men",
        price: "549",
        place: "Ships to India ",
    },

    {
        image: "./img/h2.webp",
        name: "Amazon Essentials Men's Regular-Fit Quick-Dry Golf Polo Shirt",
        number: "23,381",
        disc: "-8%",
        category: "men",
        price: "499",
        place: "Ships to India ",
    },
    {
        image: "./img/j12.webp",
        name: "John Deere Boys' Trademark Baseball Cap",
        number: "1,146",
        disc: "-5%",
        category: "kids",
        price: "349",
        place: "Ships to India ",
    },
    {
        image: "./img/i10.webp",
        name: " The Drop Women's Monika Flat H-Band Slide Sandal",
        number: "6,753",
        disc: "",
        category: "women",
        price: "999",
        place: "Ships to India ",
    },

    {
        image: "./img/i11.webp",
        name: "Marc Jacobs Women's Snapshot Crossbody Bag",
        number: "1,141",
        disc: "-13%",
        category: "women",
        price: "1149",
        place: "Ships to India ",
    },
    {
        image: "./img/i3.jpg",
        name: "MakeMeChic Women's Summer Crop Top Solid Short Sleeve Twist Front Tee T-Shirt",
        number: "5,567",
        disc: "-11%",
        category: "women",
        price: "699",
        place: "Ships to India ",
    },
    {
        image: "./img/h3.webp",
        name: "Wrangler Authentics Men's Short Sleeve Henley Tee",
        number: "8,430",
        disc: "",
        category: "men",
        price: "799",
        place: "Ships to India ",
    },
    {
        image: "./img/i1.webp",
        name: "Women's Floral Print Puff Sleeve Kimono Cardigan Loose Cover Up Casual Blouse Tops ",
        number: "3,451",
        disc: "-15%",
        category: "women",
        price: "449",
        place: "Ships to India ",
    },

    {
        image: "./img/h4.webp",
        name: "Essentials Men's Regular-Fit Short-Sleeve Poplin Shirt",
        number: "11,234",
        disc: "-24%",
        category: "men",
        price: "1199",
        place: "Ships to India ",
    },
    {
        image: "./img/h5.webp",
        name: "Essentials Men's Slim-Fit Casual Stretch Khaki Pant",
        number: "6,346",
        disc: "",
        category: "men",
        price: "999",
        place: "Ships to India ",
    },
    {
        image: "./img/h6.webp",
        name: " Essentials Men's Slim-Fit Stretch Golf Pant",
        number: "2,478",
        disc: "-12%",
        category: "men",
        price: "1299",
        place: "Ships to India ",
    },
    {
        image: "./img/h7.webp",
        name: "TBMPOY Men's Lightweight Hiking Pants Breathable Mountain Camping Fishing Running Active Jogger Pant",
        number: "4,446",
        disc: "-8%",
        category: "men",
        price: "799",
        place: "Ships to India ",
    },
    {
        image: "./img/j10.webp",
        name: "Merrell Unisex-Child Core Chameleon 7 Access Mid WTRPF Hiking Boot",
        number: "1,478",
        disc: "-12%",
        category: "kids",
        price: "1999",
        place: "Ships to India ",
    },
    {
        image: "./img/i9.webp",
        name: "Amazon Essentials Women's Square Toe Slingback Flat",
        number: "8,478",
        disc: "-22%",
        category: "women",
        price: "699",
        place: "Ships to India ",
    },
    {
        image: "./img/j11.webp",
        name: "The Hat Depot Kids Washed Low Profile Cotton and Denim Plain Baseball Cap Hat",
        number: "541",
        disc: "-8%",
        category: "kids",
        price: "249",
        place: "Ships to India ",
    },

    {
        image: "./img/h8.webp",
        name: " New Balance Men's 510 V5 Trail Running Shoe",
        number: "6,546",
        disc: "-25%",
        category: "men",
        price: "2999",
        place: "Ships to India ",
    },
    {
        image: "./img/h9.webp",
        name: " Under Armour Men's Charged Commit Tr 3, Mod Gray (105)/Black, 15 Medium US",
        number: "3,753",
        disc: "-35%",
        category: "men",
        price: "3499",
        place: "Ships to India ",
    },
    {
        image: "./img/i12.webp",
        name: "ALDO Women's Agrelin Crossbody Bag",
        number: "2,446",
        disc: "-12%",
        category: "women",
        price: "999",
        place: "Ships to India ",
    },
    {
        image: "./img/h10.webp",
        name: " Essentials Men's Slim-Fit Stretch Golf Pant",
        number: "2,478",
        disc: "-12%",
        category: "men",
        price: "1299",
        place: "Ships to India ",
    },
    {
        image: "./img/h11.webp",
        name: "ZENOTTIC Polarized Sunglasses for Men Lightweight TR90 Frame UV400 Protection Square Sun Glasses",
        number: "5,141",
        disc: "-43%",
        category: "men",
        price: "2399",
        place: "Ships to India ",
    },
    {
        image: "./img/h12.webp",
        name: " Invicta Men's Specialty Quartz Watch with Stainless Steel Band, Silver (Model: 6620)",
        number: "6,446",
        disc: "-36%",
        category: "men",
        price: "3999",
        place: "Ships to India ",
    },

    {
        image: "./img/i4.jpg",
        name: "VICHYIE Womens Ribbed Knit Henley Long Sleeves Tunic Lace Tops V Neck..",
        number: "7,467",
        disc: "-15%",
        category: "women",
        price: "399",
        place: "Ships to India ",
    },
    {
        image: "./img/i5.jpg",
        name: "Womens Tops Casual Short Sleeve Square Neck Shirts Puff Sleeve Tshirts Loose Casual Blouse Summer Tee",
        number: "10,358",
        disc: "-24%",
        category: "women",
        price: "899",
        place: "Ships to India ",
    },
    {
        image: "./img/i6.jpg",
        name: "BALEAF Women's Crop Tops Workout Cropped Tank Tops Athletic Muscle Shirts ",
        number: "3,366",
        disc: "-26%",
        category: "women",
        price: "1299",
        place: "Ships to India ",
    },
    {
        image: "./img/i7.webp",
        name: "WallFlower Women's Instastretch Bling Luscious Curvy Bootcut Jeans",
        number: "3,463",
        disc: "",
        category: "women",
        price: "1299",
        place: "Ships to India ",
    },
    {
        image: "./img/i8.webp",
        name: "Gloria Vanderbilt womens Mandie Signature Fit High Rise Straight Leg",
        number: "8,546",
        disc: "-20%",
        category: "women",
        price: "1199",
        place: "Ships to India ",
    },

    {
        image: "./img/j1.webp",
        name: "Kids Little Boys Girls Baby Red Plaid Flannel Long Sleeve Button Down Flannel Shirt Plaid Tops Girl Boy",
        number: "6,531",
        disc: "-10%",
        category: "kids",
        price: "349",
        place: "Ships to India ",
    },

    {
        image: "./img/j2.webp",
        name: "YiZYiF Kids Girls Basic 2 Piece Active Outfit Crop Top and Shorts Set for Gymnastics/Dancing/Workout",
        number: "1,381",
        disc: "-13%",
        category: "kids",
        price: "699",
        place: "Ships to India ",
    },
    {
        image: "./img/j3.webp",
        name: "3 Pieces Girls Dance Tank Top Racerback Crop Tank Top Sleeveless Dance Top for Ballet Gymnastics Dancewear",
        number: "3,537",
        disc: "",
        category: "kids",
        price: "499",
        place: "Ships to India ",
    },
    {
        image: "./img/j4.webp",
        name: "Kids Girls Neon Fluorescent Vest Crop Tops T-Shirt Tee Top Dance Wear Gymnastic Fancy Dress Age 5-14 Years",
        number: "4,657",
        disc: "-5%",
        category: "kids",
        price: "449",
        place: "Ships to India ",
    },
    {
        image: "./img/j5.webp",
        name: "Toddler Girls Sweatshirts Long Sleeve Tops Kids Pullover Bunny Unicorn Graphic Print Hoodies",
        number: "3,534",
        disc: "-24%",
        category: "kids",
        price: "699",
        place: "Ships to India ",
    },
    {
        image: "./img/j6.jpg",
        name: "Capezio Girls' Turtleneck Long Sleeve Top",
        number: "1,366",
        disc: "",
        category: "kids",
        price: "399",
        place: "Ships to India ",
    },
    {
        image: "./img/j7.jpg",
        name: "Boys' Short Sleeve Polo Shirt Kids Performance Moisture Wicking Shirt Classic Polo Embroidery Logo Boys Clothes",
        number: "1,443",
        disc: "",
        category: "kids",
        price: "699",
        place: "Ships to India ",
    },
    {
        image: "./img/j8.webp",
        name: "Under Armour Unisex-Child Pursuit 3 Alternate Closure Running Shoe",
        number: "546",
        disc: "-3%",
        category: "kids",
        price: "2399",
        place: "Ships to India ",
    },
    {
        image: "./img/j9.webp",
        name: " Skechers Unisex-Child Star Sparks Sneaker",
        number: "753",
        disc: "-10%",
        category: "kids",
        price: "1499",
        place: "Ships to India ",
    },
];

export default Menu;