const Menu = [{
        image: "./img/ka1.webp",
        name: "T-Shirts",
        from1: "399",
        from2: "1999",
        category: "topwear",
    },
    {
        image: "./img/ka2.webp",
        name: "Shirts",
        from1: "399",
        from2: "1499",
        category: "topwear",
    },
    {
        image: "./img/ka3.webp",
        name: "Sweatshirts",
        from1: "599",
        from2: "1499",
        category: "topwear",
    },
    {
        image: "./img/ka4.webp",
        name: "Jackets",
        from1: "999",
        from2: "2499",
        category: "topwear",
    },

    {
        image: "./img/ka5.webp",
        name: "Blazzers",
        from1: "1199",
        from2: "2999",
        category: "topwear",
    },
    {
        image: "./img/kb1.webp",
        name: "Jeans",
        from1: "799",
        from2: "1999",
        category: "bottomwear",
    },
    {
        image: "./img/kb2.webp",
        name: "Trousers",
        from1: "699",
        from2: "1499",
        category: "bottomwear",
    },
    {
        image: "./img/kb3.webp",
        name: "Shorts",
        from1: "499",
        from2: "999",
        category: "bottomwear",
    },
    {
        image: "./img/kb4.webp",
        name: "Track Pants",
        from1: "999",
        from2: "1999",
        category: "bottomwear",
    },
    {
        image: "./img/kb5.webp",
        name: "Joggers",
        from1: "799",
        from2: "1499",
        category: "bottomwear",
    },
    {
        image: "./img/kc1.webp",
        name: "Boxers",
        from1: "299",
        from2: "699",
        category: "innerwear",
    },
    {
        image: "./img/kc2.webp",
        name: "Briefs",
        from1: "199",
        from2: "499",
        category: "innerwear",
    },
    {
        image: "./img/kc3.webp",
        name: "Vests",
        from1: "299",
        from2: "699",
        category: "innerwear",
    },
    {
        image: "./img/kc4.webp",
        name: "Loungewear",
        from1: "399",
        from2: "699",
        category: "innerwear",
    },
    {
        image: "./img/kc5.webp",
        name: "Thermals",
        from1: "299",
        from2: "699",
        category: "innerwear",
    },
    {
        image: "./img/kd1.webp",
        name: "Casuals",
        from1: "599",
        from2: "1699",
        category: "footwear",
    },
    {
        image: "./img/kd2.webp",
        name: "Sports",
        from1: "999",
        from2: "2499",
        category: "footwear",
    },
    {
        image: "./img/kd3.webp",
        name: "Formals",
        from1: "1299",
        from2: "1999",
        category: "footwear",
    },
    {
        image: "./img/kd4.webp",
        name: "Sneakers",
        from1: "699",
        from2: "3999",
        category: "footwear",
    },
    {
        image: "./img/kd5.webp",
        name: "Flip Flops",
        from1: "299",
        from2: "999",
        category: "footwear",
    },
    {
        image: "./img/ke1.webp",
        name: "Kurtas",
        from1: "1199",
        from2: "2499",
        category: "festivewear",
    },

    {
        image: "./img/ke2.webp",
        name: "Sherwanis",
        from1: "1499",
        from2: "2999",
        category: "festivewear",
    },
    {
        image: "./img/kf1.webp",
        name: "Sunglass",
        from1: "499",
        from2: "1999",
        category: "accessories",
    },
    {
        image: "./img/kf2.webp",
        name: "Watch",
        from1: "999",
        from2: "1999",
        category: "accessories",
    },
    {
        image: "./img/kf3.webp",
        name: "Caps",
        from1: "399",
        from2: "1499",
        category: "accessories",
    },
    {
        image: "./img/kf4.webp",
        name: "Belts",
        from1: "199",
        from2: "899",
        category: "accessories",
    },
];

export default Menu;