const Menu = [{
        image: "./img/la1.webp",
        name: "Suits",
        from1: "599",
        from2: "1999",
        category: "indianwear",
    },
    {
        image: "./img/la2.webp",
        name: "Sarres",
        from1: "1499",
        from2: "2499",
        category: "indianwear",
    },
    {
        image: "./img/la3.webp",
        name: "Plazzo",
        from1: "999",
        from2: "1499",
        category: "indianwear",
    },
    {
        image: "./img/la4.webp",
        name: "Lehenga",
        from1: "1199",
        from2: "2999",
        category: "indianwear",
    },
    {
        image: "./img/lb1.webp",
        name: "Tops",
        from1: "299",
        from2: "999",
        category: "westernwear",
    },
    {
        image: "./img/lb2.webp",
        name: "Jeans",
        from1: "599",
        from2: "1999",
        category: "westernwear",
    },
    {
        image: "./img/lb3.webp",
        name: "Shorts",
        from1: "299",
        from2: "699",
        category: "westernwear",
    },
    {
        image: "./img/lb4.webp",
        name: "Jackets",
        from1: "1199",
        from2: "2499",
        category: "westernwear",
    },
    {
        image: "./img/lc1.webp",
        name: "Flats",
        from1: "499",
        from2: "1499",
        category: "footwear",
    },
    {
        image: "./img/lc2.webp",
        name: "Casuals",
        from1: "499",
        from2: "1999",
        category: "footwear",
    },
    {
        image: "./img/lc3.webp",
        name: "Heels",
        from1: "699",
        from2: "1699",
        category: "footwear",
    },
    {
        image: "./img/lc4.webp",
        name: "Boots",
        from1: "1499",
        from2: "2999",
        category: "footwear",
    },
    {
        image: "./img/ld1.webp",
        name: "Hand Bags",
        from1: "499",
        from2: "999",
        category: "accessories",
    },
    {
        image: "./img/ld2.webp",
        name: "Sunglasses",
        from1: "399",
        from2: "1199",
        category: "accessories",
    },
    {
        image: "./img/ld3.webp",
        name: "Caps",
        from1: "499",
        from2: "999",
        category: "accessories",
    },
];
export default Menu;